version: '3.8'

services:
  node-red:
    build: .
    ports:
      - "1880:1880"
    environment:
      - NODE_RED_USERNAME=${NODE_RED_USERNAME}
      - NODE_RED_PASSWORD_HASH=${NODE_RED_PASSWORD_HASH}
    volumes:
      - node-red-data:/data
  
volumes:
  node-red-data: